[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -o index-compiled.css --minify"]

[[hooks]]
stage = "post_build"
command = "sh"
command_arguments = ["-c", "rm index-compiled.css"]
