name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: "stable"
          target: wasm32-unknown-unknown
          override: true
          profile: minimal
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/trunk-action@v0.1.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: trunk build --release
